### ISSUE TITLE
PermissionError on Windows

### ISSUE THREAD

**Issue by fhg-isi** [ftpsolutions/python-third-party-license-file-generator#16]
I tried to use following command on Windows with WinPython

python -m third_party_license_file_generator -r requirements.txt -p C:\python_env\App\WinPython\python-3.11.1.amd64

and got

```
mixing requirements paths and Python paths together as follows:
        'requirements.txt' - 'C:\\python_env\\App\\WinPython\\python-3.11.1.amd64'

working on license summary...

handling 'requirements.txt' with 'C:\\python_env\\App\\WinPython\\python-3.11.1.amd64' ...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\third_party_license_file_generator\__main__.py", line 185, in <module>
    SitePackages(
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\third_party_license_file_generator\site_packages.py", line 130, in __init__
    self.run()
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\third_party_license_file_generator\site_packages.py", line 370, in run
    self._read_all_module_metadatas_and_license_files()
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\third_party_license_file_generator\site_packages.py", line 236, in _read_all_module_metadatas_and_license_files
    site_packages_path = self._get_site_packages_folder()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\third_party_license_file_generator\site_packages.py", line 175, in _get_site_packages_folder
    out, err, returncode = _run_subprocess("{0} -m site".format(self._python_path))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\site-packages\third_party_license_file_generator\site_packages.py", line 25, in _run_subprocess
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python_env\App\WinPython\python-3.11.1.amd64\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied
```

=> How to resolve this?

**Comment by initialed85** [comment]
Might just be a Windows folder permissions thing- if you’re running from a command prompt, try changing that to a command prompt with admin privileges.

I don’t really know for sure though, any time I touch Windows I come out in a rash so I try to stay away from it

**Comment by StephenGoodall** [comment]
@fhg-isi
I know this is an old issue.......but you could try putting \python.exe on the end of the -p argument - that seemed to work for me
